# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_CI <- function(beta_hat, se_beta_hat) {
    .Call(`_lm_hua_calculate_CI`, beta_hat, se_beta_hat)
}

